acronym_app/acronym_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('core.urls','core'), namespace='core')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acronym_app/core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('',views.index,name='index'),
]

acronym_app/core/models.py
from django.db import models

# Create your models here.
class Acronym(models.Model):
    """An acronym that user wants to know about"""
    acronym = models.CharField(max_length=20)
    expanded_form = models.CharField(max_length=200)
    about = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def save(self, force_insert=False, force_update=False):
        self.acronym = self.acronym.upper()
        super(Acronym, self).save(force_insert,force_update)

    def __str__(self):
        return self.acronym

acronym_app/core/views.py
from django.shortcuts import render
from .models import Acronym

# Create your views here.
def index(request):
    """The home page view for acronym app."""
    acronym_details = ""
    if request.method == "POST":
        try:
            acronym_details = Acronym.objects.get(acronym=request.POST.get('acronym').upper()) 
        except:
            acronym_details = "nf"
    
    content = {
        'acronym_details' : acronym_details
    }
    return render(request,'core/index.html',content)

acronym_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
    <title>Acronym App</title>
</head>
<body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container-fluid" >
            <a class="navbar-brand" href="{% url 'core:index' %}">Honeywell Acronym App</a>
            <button type="button" class="navbar-toggler"
                data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-expanded="false" aria-controls="navbarSupportedContent" aria-label="Toggle navigation">
            </button>
            <div id="navbarSupportedContent" class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
                <ul class="nav navbar-nav navbar-right"></ul>
            </div>
        </div>
    </nav>

    <div class="container-fluid">
        <div class="page-body">
            {% block content %}{% endblock content %}
        </div>
    </div> <!--  /container -->

    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
</body>
</html>

acronym_app/templates/core/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<div class="row">
    <p>
        This app helps you search for any cFMS acronym you want to know about.
    </p>
<div>

<form class="row g-3" action="{% url 'core:index' %}" method="post">
    {% csrf_token %}
    <div class="col-md-3">
        <input class="form-control" type="text" name="acronym" placeholder="Enter acronym to get its details...">
    </div>
    <div class="col-md-3">
        <button class="btn btn-primary" type="submit">Search</button>
    </div>
</form>

{% if acronym_details != "" %}

<div class="card" style="margin-top: 30px;">
    <div class="card-header">
        {% if acronym_details == "nf" %}
        Sorry &#128531, no data found!
    </div>
        {% else %}
        {{acronym_details.expanded_form}}
    </div>
    <div class="card-body">
        {{acronym_details.about}}
    </div>
    {% endif %}
</div>
{% endif %}

{% endblock content %}